#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Contest Management System - http://cms-dev.github.io/
# Copyright © 2025 Chuyang Wang <mail@chuyang-wang.de>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from __future__ import absolute_import
from __future__ import print_function
from __future__ import unicode_literals

import logging
import sys

from cms import ConfigError, default_argument_parser
from cms.db import ask_for_contest, test_db_connection
from cms.service.DiscordBotService import DiscordBotService


logger = logging.getLogger(__name__)


def main():
    test_db_connection()
    
    return default_argument_parser("Discord Bot Service for CMS",
                                   DiscordBotService,
                                   ask_contest=ask_for_contest).run()

if __name__ == "__main__":
    try:
        sys.exit(0 if main() else 1)
    except ConfigError as error:
        logger.critical(str(error))
        sys.exit(1)
